// Package handler provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package handler

import (
	"github.com/go-chi/chi"
	"net/http"
)

type ServerInterface interface {
	// サーバーの状態を返します (GET /health)
	OpenapitutorialControllerHealthCall(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// OpenapitutorialControllerHealthCall operation middleware
func (siw *ServerInterfaceWrapper) OpenapitutorialControllerHealthCall(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	siw.Handler.OpenapitutorialControllerHealthCall(w, r.WithContext(ctx))
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerFromMux(si, chi.NewRouter())
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	r.Group(func(r chi.Router) {

		r.Get("/health", wrapper.OpenapitutorialControllerHealthCall)
	})

	return r
}

