// Package handler provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package handler

// GetHealthResponse defines model for get_health_response.
type GetHealthResponse struct {
	Status string `json:"status"`
}

